---
name: "Setup Release"
description: "Parse the changelog and setup the release parameters."
author: "LizardByte"

inputs:
  changelog_path:
    description: "Path to the changelog file, relative to the GitHub workspace."
    default: "CHANGELOG.md"
    required: false
  dotnet:
    description: "Whether to create a dotnet version (4 components, e.g. yyyy.mmdd.hhmm.ss)."
    default: 'false'
    required: false
  fail_on_events_api_error:
    description: "Whether to fail if the GitHub Events API returns an error."
    default: 'false'
    required: false
  github_token:
    description: "GitHub token to use for API requests."
    required: true
  include_tag_prefix_in_output:
    description: "Whether to include the tag prefix in the output."
    default: 'true'
    required: false
  tag_prefix:
    description: |
      The tag prefix. This will be used when searching for existing releases in GitHub API.
      This should not be included in the version within the changelog.
    default: "v"
    required: false

outputs:
  changelog_changes:
    description: "List of changes in the latest version."
  changelog_date:
    description: "Date of the latest version in the format: `yyyy.m.d`"
  changelog_exists:
    description: "Whether the changelog exists."
  changelog_release_exists:
    description: "Whether the release exists in GitHub."
  changelog_url:
    description: "URL to the latest version in the changelog."
  changelog_version:
    description: "Latest version in the changelog."
  publish_stable_release:
    description: "Whether to publish a stable release."
  release_tag:
    description: "Tag of the release to make. e.g. `vYYYY.M.D-Build` or `vYYYY.M.D`"
  release_version:
    description: "Version of the release to make."

runs:
  using: "docker"
  image: "Dockerfile"
